
package interfaces;
import entidades.*;

/**
 *
 * @author alumno
 */
public class JFBatalla extends javax.swing.JFrame {
    Pokemon miPokemon = new Pokemon("Pokemon 1");
    Pokemon rival = new Pokemon("Pokemon 2");
    int conOp = 0;
    int conMp = 0;   
    

    /**
     * Creates new form JFPresentacion
     */
    //
    public JFBatalla() {
        initComponents();
        setLocationRelativeTo(null);
        MostrarImagen();
        MostrarPokemon();
        MostrarNombre();
        jLabel5.setText(JFPresentacion.nombre);
        jLabelMiPo.setText(miPokemon.MostrarEstado());
        jLabelMiCo.setText(rival.MostrarEstado());
        jLabel9.setText(miPokemon.MostrarNivel());
        jLabel8.setText(rival.MostrarNivel());
        
        
    }
    public void MostrarImagen(){
        if (JFPresentacion.genero == "Femenino" ){
            jLabel17.setVisible(true);
            jLabel2.setVisible(false);            
        }
        else if ((JFPresentacion.genero == "Masculino" )) {
            jLabel17.setVisible(false);
            jLabel2.setVisible(true);
            
        }
        
    }
    public void MostrarPokemon(){
        if(JFSeleccionPokemon.pokemonPulsado == "a"){
            jLabelS1.setVisible(false);
            jLabelC1.setVisible(true);
            jLabelB1.setVisible(false);
            jLabelS2.setVisible(false);
            jLabelC2.setVisible(false);
            jLabelB2.setVisible(true);
            
        }
        else if(JFSeleccionPokemon.pokemonPulsado == "b"){
            jLabelS1.setVisible(false);
            jLabelC1.setVisible(false);
            jLabelB1.setVisible(true);
            jLabelS2.setVisible(true);
            jLabelC2.setVisible(false);
            jLabelB2.setVisible(false);
            
        }
        else if (JFSeleccionPokemon.pokemonPulsado == "c"){
            jLabelS1.setVisible(true);
            jLabelC1.setVisible(false);
            jLabelB1.setVisible(false);
            jLabelS2.setVisible(false);
            jLabelC2.setVisible(true);
            jLabelB2.setVisible(false);
        }
        
    }
    public void MostrarNombre(){
        if (JFSeleccionPokemon.pokemonPulsado == "a" && JFSobrenombre.opcionPulsada == "g"){
            jLabel13.setText(JFSobrenombre.apodo);
            
            
        }
        else if (JFSeleccionPokemon.pokemonPulsado == "a" && JFSobrenombre.opcionPulsada == "o"){
            jLabel13.setText("Bolbasour");
            jLabel14.setText("Charmander");
           
        }
        else if (JFSeleccionPokemon.pokemonPulsado == "b" && JFSobrenombre.opcionPulsada == "g"){
            jLabel13.setText(JFSobrenombre.apodo);
            jLabel14.setText("Bolbasour");
        }
        else if (JFSeleccionPokemon.pokemonPulsado == "b" && JFSobrenombre.opcionPulsada == "o"){
            jLabel13.setText("Squirtle");
            jLabel14.setText("Bolbasour");
            
        }
        else if (JFSeleccionPokemon.pokemonPulsado == "c" && JFSobrenombre.opcionPulsada == "g"){
            jLabel13.setText(JFSobrenombre.apodo);
            jLabel14.setText("Squirtle");
        }
        else if (JFSeleccionPokemon.pokemonPulsado == "c" && JFSobrenombre.opcionPulsada == "o"){
            jLabel13.setText("Charmander");
            jLabel14.setText("Squirtle");
        }
    }
   
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelMiPo = new javax.swing.JLabel();
        jLabelMiCo = new javax.swing.JLabel();
        jLabelS2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButtonAtacar = new javax.swing.JButton();
        jButtonRendi = new javax.swing.JButton();
        jButtonPocion = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabelS1 = new javax.swing.JLabel();
        jLabelB1 = new javax.swing.JLabel();
        jLabelC2 = new javax.swing.JLabel();
        jLabelC1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelB2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/entre.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 207, 414));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/entrena1.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Severous Ouk ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("vgfr");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 480, 220, 30));

        jLabelMiPo.setText("Pokemon 2// *** HP");
        getContentPane().add(jLabelMiPo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, -1, -1));

        jLabelMiCo.setText("Pokemon 1// *** HP");
        getContentPane().add(jLabelMiCo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        jLabelS2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Squirtle (1).png"))); // NOI18N
        getContentPane().add(jLabelS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 160, 150));

        jLabel8.setText("NIVEL X");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, -1, -1));

        jLabel9.setText("NIVEL X");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, -1, -1));

        jButtonAtacar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAtacar.setText("Atacar");
        jButtonAtacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtacarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtacar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, -1, -1));

        jButtonRendi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRendi.setText("Rendirse");
        jButtonRendi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRendiActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRendi, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, -1, -1));

        jButtonPocion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonPocion.setText("Usar poción");
        jButtonPocion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPocionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPocion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/entrenadora.png"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(869, 60, 210, -1));

        jLabelS1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Squirtle (1).png"))); // NOI18N
        getContentPane().add(jLabelS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 160, 150));

        jLabelB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bolbii.png"))); // NOI18N
        getContentPane().add(jLabelB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 160, 140));

        jLabelC2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/char2.png"))); // NOI18N
        getContentPane().add(jLabelC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, -1, -1));

        jLabelC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/char2.png"))); // NOI18N
        getContentPane().add(jLabelC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/jiji2.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 600, 130));

        jButtonExit.setText("jButton1");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 560, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 490, 170));

        jLabelB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bolbii.png"))); // NOI18N
        getContentPane().add(jLabelB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 160, 140));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("aaaaa");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 120, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Squirtle");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estadio3.jpg"))); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    void AnalizarSituacion() {
        if (miPokemon.vida == 0) {
            jTextArea1.append(miPokemon.nombre 
                    + " Ya no puede continuar. "
                    + rival.nombre + " gana.");
            
            jButtonAtacar.setEnabled(false);
            jButtonRendi.setEnabled(false);
            jButtonPocion.setEnabled(false);
        }
        
        if (rival.vida == 0) {
            jTextArea1.append(rival.nombre 
                    + " Ya no puede continuar. "
                    + miPokemon.nombre + " gana.");
            
            jButtonAtacar.setEnabled(false);
            jButtonRendi.setEnabled(false);
            jButtonPocion.setEnabled(false);
        }
    }
    private void jButtonPocionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPocionActionPerformed
        if (conMp ==3){
            jButtonPocion.setEnabled(false);
            
        }
        else {
            String resultado3 = miPokemon.Pocion(miPokemon);
            conMp = conMp +1;
            jTextArea1.append(resultado3 + "\n");
            
            int probAtac = (int)(Math.random()*100);
            if (probAtac<=25 && conOp <3){
                String resultado2 = rival.Pocion(rival);
                conOp = conOp +1;
                jTextArea1.append(resultado2 + "\n" +"\n");
            }
            else {
                String resultado2 = rival.AtacarVentaja(miPokemon);
            jTextArea1.append(resultado2 + "\n" + "\n");
            }
        }
                        
        jLabelMiPo.setText(miPokemon.MostrarEstado());
        jLabelMiCo.setText(rival.MostrarEstado());
        
        AnalizarSituacion();
    }//GEN-LAST:event_jButtonPocionActionPerformed
    
    private void jButtonAtacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtacarActionPerformed
        String resultado = miPokemon.Atacar(rival);       
        jTextArea1.append(resultado + "\n");

        int probAtac = (int)(Math.random()*100);
        if (probAtac<=25 && conOp <3){
            String resultado2 = rival.Pocion(rival);
            conOp = conOp +1;
            jTextArea1.append(resultado2 + "\n" +"\n");
            
        }
        else {
            String resultado2 = rival.AtacarVentaja(miPokemon);
            jTextArea1.append(resultado2 + "\n" + "\n");
        }
        
        
        jLabelMiPo.setText(miPokemon.MostrarEstado());
        jLabelMiCo.setText(rival.MostrarEstado());
        
        AnalizarSituacion();
    }//GEN-LAST:event_jButtonAtacarActionPerformed

    private void jButtonRendiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRendiActionPerformed
        String resultado4 = miPokemon.Rendirse(miPokemon);
        jTextArea1.append(resultado4 + "\n" + rival.nombre + ", gana la batalla");
        
        jButtonAtacar.setEnabled(false);
        jButtonRendi.setEnabled(false);
        jButtonPocion.setEnabled(false);
    }//GEN-LAST:event_jButtonRendiActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFBatalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFBatalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFBatalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFBatalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFBatalla().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtacar;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonPocion;
    private javax.swing.JButton jButtonRendi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelB1;
    private javax.swing.JLabel jLabelB2;
    private javax.swing.JLabel jLabelC1;
    private javax.swing.JLabel jLabelC2;
    private javax.swing.JLabel jLabelMiCo;
    private javax.swing.JLabel jLabelMiPo;
    private javax.swing.JLabel jLabelS1;
    private javax.swing.JLabel jLabelS2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
