/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

/**
 *
 * @author alumno
 */
public class JFSeleccionPokemon extends javax.swing.JFrame {
    public static String pokemonPulsado;

    /**
     * Creates new form JFSeleccionPokemon
     */
    public JFSeleccionPokemon() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Squirtle = new javax.swing.JLabel();
        Bolbausor = new javax.swing.JLabel();
        Charmander = new javax.swing.JLabel();
        jButton1square = new javax.swing.JButton();
        jButton2bol = new javax.swing.JButton();
        jButton3char = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("Seleccione un Pokemon");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        Squirtle.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        Squirtle.setText("Squirtle");
        getContentPane().add(Squirtle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        Bolbausor.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        Bolbausor.setText("Bolbausor");
        getContentPane().add(Bolbausor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        Charmander.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        Charmander.setText("Charmander");
        getContentPane().add(Charmander, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        jButton1square.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/square.jpg"))); // NOI18N
        jButton1square.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1squareActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1square, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 80, 70));

        jButton2bol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bolba.png"))); // NOI18N
        jButton2bol.setToolTipText("");
        jButton2bol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2bolActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2bol, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 80, 80));

        jButton3char.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/charmander1.jpg"))); // NOI18N
        jButton3char.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3charActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3char, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 80, 80));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo de eleccion2.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2bolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2bolActionPerformed
        JFSobrenombre frame = new JFSobrenombre();
        pokemonPulsado = "a";
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2bolActionPerformed

    private void jButton1squareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1squareActionPerformed
        JFSobrenombre frame = new JFSobrenombre();
        frame.setVisible(true);
        pokemonPulsado = "b";
        dispose();
    }//GEN-LAST:event_jButton1squareActionPerformed

    private void jButton3charActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3charActionPerformed
        JFSobrenombre frame = new JFSobrenombre();
        frame.setVisible(true);
        pokemonPulsado = "c";
        dispose();
    }//GEN-LAST:event_jButton3charActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFSeleccionPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFSeleccionPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFSeleccionPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFSeleccionPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFSeleccionPokemon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bolbausor;
    private javax.swing.JLabel Charmander;
    private javax.swing.JLabel Squirtle;
    public static javax.swing.JButton jButton1square;
    public static javax.swing.JButton jButton2bol;
    public static javax.swing.JButton jButton3char;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
