/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

/**
 *
 * @author Marielena
 */
public class JFVersus extends javax.swing.JFrame {
    public static String nomfiP;
    public static String nomfiR;
    /**
     * Creates new form JFVersus
     */
    public JFVersus() {
        initComponents();
        setLocationRelativeTo(null);
        MostrarPokemon();
        MostrarNombre();
    }
    public void MostrarPokemon(){
         if("a".equals(JFSeleccionPokemon.pokemonPulsado)){
            jLBol1.setVisible(true);
            jLSqui1.setVisible(false);
            jLChar1.setVisible(false);
            jLBol2.setVisible(false);
            jLSqui2.setVisible(false);
            jLChar2.setVisible(true);
            
        }
        else if("b".equals(JFSeleccionPokemon.pokemonPulsado)){
            jLBol1.setVisible(false);
            jLSqui1.setVisible(true);
            jLChar1.setVisible(false);
            jLBol2.setVisible(true);
            jLSqui2.setVisible(false);
            jLChar2.setVisible(false);
        }
            
        else if ("c".equals(JFSeleccionPokemon.pokemonPulsado)){
            jLBol1.setVisible(false);
            jLSqui1.setVisible(false);
            jLChar1.setVisible(true);
            jLBol2.setVisible(false);
            jLSqui2.setVisible(true);
            jLChar2.setVisible(false);
        }
        
    }
    public void MostrarNombre(){
        if (JFSeleccionPokemon.pokemonPulsado == "a" && JFSobrenombre.opcionPulsada == "g"){
            jLabelNomMipok.setText(JFSobrenombre.apodo);
            jLabelNomPokRiv.setText("Charmander");
            
        }
        else if ("a".equals(JFSeleccionPokemon.pokemonPulsado) && "o".equals(JFSobrenombre.opcionPulsada)){
            jLabelNomMipok.setText("Bolbasour");
            jLabelNomPokRiv.setText("Charmander");
           
        }
        else if ("b".equals(JFSeleccionPokemon.pokemonPulsado) && "g".equals(JFSobrenombre.opcionPulsada)){
            jLabelNomMipok.setText(JFSobrenombre.apodo);
            jLabelNomPokRiv.setText("Bolbasour");
        }
        else if ("b".equals(JFSeleccionPokemon.pokemonPulsado) && "o".equals(JFSobrenombre.opcionPulsada)){
            jLabelNomMipok.setText("Squirtle");
            jLabelNomPokRiv.setText("Bolbasour");
            
        }
        else if ("c".equals(JFSeleccionPokemon.pokemonPulsado) && "g".equals(JFSobrenombre.opcionPulsada)){
            jLabelNomMipok.setText(JFSobrenombre.apodo);
            jLabelNomPokRiv.setText("Squirtle");
        }
        else if ("c".equals(JFSeleccionPokemon.pokemonPulsado) && "o".equals(JFSobrenombre.opcionPulsada)){
            jLabelNomMipok.setText("Charmander");
            jLabelNomPokRiv.setText("Squirtle");
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLChar2 = new javax.swing.JLabel();
        jLChar1 = new javax.swing.JLabel();
        jLSqui2 = new javax.swing.JLabel();
        jLSqui1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLBol1 = new javax.swing.JLabel();
        jLBol2 = new javax.swing.JLabel();
        jLabelNomPokRiv = new javax.swing.JLabel();
        jLabelNomMipok = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLChar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/char2.png"))); // NOI18N
        getContentPane().add(jLChar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, 140));

        jLChar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/char2.png"))); // NOI18N
        getContentPane().add(jLChar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLSqui2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Squirtle (1).png"))); // NOI18N
        getContentPane().add(jLSqui2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));

        jLSqui1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Squirtle (1).png"))); // NOI18N
        getContentPane().add(jLSqui1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Batallar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 110, 30));

        jLBol1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bolbii.png"))); // NOI18N
        getContentPane().add(jLBol1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 150, -1));

        jLBol2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bolbii.png"))); // NOI18N
        getContentPane().add(jLBol2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, -1, -1));

        jLabelNomPokRiv.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelNomPokRiv.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomPokRiv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNomPokRiv.setText("jLabel3");
        getContentPane().add(jLabelNomPokRiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, -1, -1));

        jLabelNomMipok.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelNomMipok.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomMipok.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNomMipok.setText("jLabel2");
        getContentPane().add(jLabelNomMipok, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/versus.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 584, 584));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         
               
        nomfiP = jLabelNomMipok.getText();
        nomfiR = jLabelNomPokRiv.getText();
        
        JFBatalla frame = new JFBatalla();
        frame.setVisible(true);
        dispose();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFVersus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFVersus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFVersus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFVersus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFVersus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLBol1;
    private javax.swing.JLabel jLBol2;
    private javax.swing.JLabel jLChar1;
    private javax.swing.JLabel jLChar2;
    private javax.swing.JLabel jLSqui1;
    private javax.swing.JLabel jLSqui2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNomMipok;
    private javax.swing.JLabel jLabelNomPokRiv;
    // End of variables declaration//GEN-END:variables
}
